name: AstradalSeiges
version: ${project.version}
main: io.github.Cubicl18.AstradalSeigePlugin
api-version: 1.19
depend: [ModelEngine, UltimateAdvancementAPI]
commands:
  sieges:
    aliases: [s,sieges]
    description: commands for the AstradalSieges Plugin
    usage: /sieges







