name: AstradalSeiges
version: 1.0
main: io.github.Cubicl18.AstradalSeigePlugin
api-version: 1.19
depend: [ModelEngine]
commands:
  sieges:
    aliases: [s,sieges]
    description: commands for the AstradalSieges Plugin
    usage: /sieges
    permissions:







